# Generated by Django 4.1.7 on 2023-03-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasurko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
